//! Versioned schema migrations (TASK-008).
//!
//! sqlx-style: each migration is a versioned SQL batch applied once, in order,
//! gated by `PRAGMA user_version`. Each migration runs inside an IMMEDIATE
//! transaction, so two app instances starting concurrently serialize instead of
//! double-applying. Only tables owned by this task live here — TASK-010/011
//! tables are added by their own later migrations.
//!
//! Rules: the list is append-only and applied migrations are never edited.

use rusqlite::{Connection, TransactionBehavior};

use crate::db::DbError;

/// One ordered schema migration.
pub struct Migration {
    /// Version number (equals `PRAGMA user_version` after the migration runs).
    pub version: i64,
    /// Short human-readable name, used in error messages.
    pub name: &'static str,
    /// SQL batch (multiple statements allowed; must not manage its own tx).
    pub sql: &'static str,
}

/// The ordered migration list. Append-only.
pub const MIGRATIONS: &[Migration] = &[
    Migration {
        version: 1,
        name: "create projects table",
        sql: r#"
            CREATE TABLE projects (
                id TEXT PRIMARY KEY,           -- uuid v4
                name TEXT NOT NULL,
                source_video_path TEXT NOT NULL,
                status TEXT NOT NULL,          -- draft/analyzed/transcribed/translated/rendered
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                settings_json TEXT             -- project-level overrides
            );
        "#,
    },
    Migration {
        version: 2,
        name: "index projects.updated_at",
        sql: r#"
            CREATE INDEX idx_projects_updated_at ON projects(updated_at);
        "#,
    },
    Migration {
        version: 3,
        name: "create jobs table",
        sql: r#"
            CREATE TABLE jobs (
                id TEXT PRIMARY KEY,           -- job_NNNN (canonical Job schema)
                project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
                type TEXT NOT NULL,            -- transcribe/translate/subtitle/render
                status TEXT NOT NULL,          -- queued/running/succeeded/failed/cancelled
                progress REAL NOT NULL DEFAULT 0,
                stage TEXT NOT NULL DEFAULT 'queued',
                error_code TEXT,
                error_message TEXT,
                error_log TEXT,
                params_json TEXT NOT NULL DEFAULT '{}',
                retry_count INTEGER NOT NULL DEFAULT 0,
                cancel_requested INTEGER NOT NULL DEFAULT 0,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                started_at TEXT,
                finished_at TEXT
            );
            CREATE INDEX idx_jobs_project_id ON jobs(project_id);
            CREATE INDEX idx_jobs_status ON jobs(status);
        "#,
    },
    Migration {
        version: 4,
        name: "create cache entries table",
        sql: r#"
            CREATE TABLE cache_entries (
                project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
                key TEXT NOT NULL,               -- canonical content-addressed key (§3.7)
                stage TEXT NOT NULL,             -- audio/stt/tr/subtitle/render
                file_name TEXT NOT NULL,         -- <stage>_<sha256(key)>
                size_bytes INTEGER NOT NULL,
                created_at TEXT NOT NULL,
                last_accessed_at TEXT NOT NULL,
                PRIMARY KEY (project_id, key)
            );
            CREATE INDEX idx_cache_entries_last_access ON cache_entries(last_accessed_at);
            CREATE INDEX idx_cache_entries_stage ON cache_entries(stage);
        "#,
    },
    Migration {
        version: 5,
        name: "create glossary + character entries tables",
        sql: r#"
            CREATE TABLE glossary_entries (
                project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
                term TEXT NOT NULL,              -- canonical term (lowercased by service)
                translation TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                PRIMARY KEY (project_id, term)
            );
            CREATE INDEX idx_glossary_entries_project ON glossary_entries(project_id);

            CREATE TABLE character_entries (
                project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
                name TEXT NOT NULL,
                description TEXT NOT NULL DEFAULT '',
                updated_at TEXT NOT NULL,
                PRIMARY KEY (project_id, name)
            );
            CREATE INDEX idx_character_entries_project ON character_entries(project_id);
        "#,
    },
    Migration {
        version: 6,
        name: "create subtitle_cues table",
        sql: r#"
            CREATE TABLE subtitle_cues (
                id TEXT PRIMARY KEY,               -- uuid v4 (generated by the Rust core)
                project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
                cue_number INTEGER NOT NULL,       -- 1-based display order (UNIQUE per project)
                start REAL NOT NULL,               -- seconds
                end REAL NOT NULL,                 -- seconds
                text TEXT NOT NULL,                -- target subtitle text (edited by the user)
                speaker TEXT,                      -- transcript speaker (editor display)
                source_text TEXT,                  -- original transcript text (editor display)
                status TEXT NOT NULL DEFAULT 'draft',  -- draft/translated/edited/approved
                style_json TEXT,                   -- optional per-cue style overrides
                updated_at TEXT NOT NULL,
                UNIQUE(project_id, cue_number)
            );
            CREATE INDEX idx_subtitle_cues_project ON subtitle_cues(project_id);
        "#,
    },
];

/// Apply every pending migration (versions greater than `user_version`) in order.
pub fn run_migrations(conn: &mut Connection) -> Result<(), DbError> {
    let current = current_version(conn)?;
    for migration in MIGRATIONS.iter().filter(|m| m.version > current) {
        apply_migration(conn, migration)?;
    }
    Ok(())
}

/// Apply one migration atomically and bump `user_version`.
///
/// `pub` so tests can simulate a partial upgrade (v1 applied, v2 pending).
pub fn apply_migration(conn: &mut Connection, migration: &Migration) -> Result<(), DbError> {
    let tx = conn.transaction_with_behavior(TransactionBehavior::Immediate)?;
    tx.execute_batch(migration.sql).map_err(|e| {
        DbError::Migration(format!(
            "migration v{} ({}) failed: {e}",
            migration.version, migration.name
        ))
    })?;
    tx.pragma_update(None, "user_version", migration.version)?;
    tx.commit().map_err(|e| {
        DbError::Migration(format!(
            "commit migration v{} ({}) failed: {e}",
            migration.version, migration.name
        ))
    })?;
    Ok(())
}

/// Current schema version (`PRAGMA user_version`).
pub fn current_version(conn: &Connection) -> Result<i64, DbError> {
    Ok(conn.pragma_query_value(None, "user_version", |r| r.get::<_, i64>(0))?)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn mem_conn() -> Connection {
        Connection::open_in_memory().expect("in-memory sqlite")
    }

    #[test]
    fn fresh_db_reaches_latest_version() {
        let mut conn = mem_conn();
        run_migrations(&mut conn).expect("migrate");
        let v: i64 = conn
            .pragma_query_value(None, "user_version", |r| r.get(0))
            .unwrap();
        assert_eq!(v, MIGRATIONS.len() as i64);
    }

    #[test]
    fn migrations_are_idempotent() {
        let mut conn = mem_conn();
        run_migrations(&mut conn).expect("run");
        run_migrations(&mut conn).expect("re-run");
        let v: i64 = conn
            .pragma_query_value(None, "user_version", |r| r.get(0))
            .unwrap();
        assert_eq!(v, MIGRATIONS.len() as i64);
    }

    #[test]
    fn v1_to_v2_preserves_existing_rows() {
        let mut conn = mem_conn();
        // Simulate a deployment that stopped at v1 with live data...
        apply_migration(&mut conn, &MIGRATIONS[0]).expect("apply v1");
        conn.execute(
            "INSERT INTO projects (id, name, source_video_path, status, created_at, updated_at)
             VALUES ('00000000-0000-4000-8000-000000000000', 'kept row', 'video.mp4', 'draft', 't0', 't0')",
            [],
        )
        .expect("seed row");
        // ...then upgrade to the latest version.
        run_migrations(&mut conn).expect("migrate to latest");
        let v: i64 = conn
            .pragma_query_value(None, "user_version", |r| r.get(0))
            .unwrap();
        assert_eq!(v, MIGRATIONS.len() as i64);

        let kept: i64 = conn
            .query_row(
                "SELECT COUNT(*) FROM projects WHERE id = '00000000-0000-4000-8000-000000000000'",
                [],
                |r| r.get(0),
            )
            .unwrap();
        assert_eq!(kept, 1, "v1→v2 must not drop data");
    }

    #[test]
    fn user_version_gates_reapplication() {
        let mut conn = mem_conn();
        run_migrations(&mut conn).expect("migrate");
        // A second run (e.g. a second app instance) sees an up-to-date
        // user_version and applies nothing further.
        let applied = run_migrations(&mut conn);
        assert!(applied.is_ok());
        let v: i64 = conn
            .pragma_query_value(None, "user_version", |r| r.get(0))
            .unwrap();
        assert_eq!(v, MIGRATIONS.len() as i64);
    }
}
