#!/usr/bin/env python3
"""Autonomous orchestrator for the AI Video Localization Studio repository.

Lifecycle:
    START -> discover current task -> launch coding agent -> implement ->
    run tests -> verify acceptance -> commit -> update persistent state ->
    discover next task -> repeat -> TASK-030 -> final MVP verification -> DONE

Usage (from the repository root):

    python scripts/autonomous_runner.py --dry-run   # preview only, no changes
    python scripts/autonomous_runner.py --status    # print current state
    python scripts/autonomous_runner.py --resume    # resume from saved state
    python scripts/autonomous_runner.py --stop      # graceful stop after safe op
    python scripts/autonomous_runner.py             # run the loop

Config lives in ``config/autonomous.json``. The coding agent CLI is detected
automatically (or set via ``agent_command``). No secrets live in config.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = REPO_ROOT / "config" / "autonomous.json"
PROGRESS_PATH = REPO_ROOT / "docs" / "AUTONOMOUS_PROGRESS.md"
HANDOFF_PATH = REPO_ROOT / "docs" / "AUTONOMOUS_HANDOFF.md"
BLOCKERS_PATH = REPO_ROOT / "docs" / "AUTONOMOUS_BLOCKERS.md"
FINAL_REPORT_PATH = REPO_ROOT / "docs" / "AUTONOMOUS_FINAL_REPORT.md"
STOP_FLAG_PATH = REPO_ROOT / "docs" / "AUTONOMOUS_STOP_FLAG"
TASKS_MD = REPO_ROOT / "TASKS.md"

sys.path.insert(0, str(Path(__file__).resolve().parent))

from autonomous_handoff import write_handoff  # noqa: E402
from autonomous_state import (  # noqa: E402
    mark_current_task,
    mark_task_failed,
    mark_task_passed,
    read_state,
    write_state,
)
from autonomous_tasks import discover_tasks, find_current_task, get_task_section  # noqa: E402
from autonomous_verify import git_log_tasks, git_status_lines, run_gates_for_layers  # noqa: E402

# Candidate coding-agent CLIs, in preference order.
AGENT_CLIS = ["opencode", "claude", "codex", "aider"]

DEFAULT_CONFIG = {
    "runner_version": "1.0",
    "agent_command": None,
    "max_task_retries": 5,
    "max_session_restarts": 20,
    "context_threshold": 0.8,
    "auto_commit": True,
    "start_task": None,
    "max_tasks_per_session": 1,
    "require_clean_git": True,
    "final_verification": True,
    "prompt_template": "scripts/autonomous_agent_prompt.md",
}


def load_config() -> dict:
    if not CONFIG_PATH.exists():
        return dict(DEFAULT_CONFIG)
    try:
        loaded = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return dict(DEFAULT_CONFIG)
    config = dict(DEFAULT_CONFIG)
    config.update(loaded)
    return config


def detect_agent(config: dict) -> list[str]:
    """Resolve the coding-agent command as an argument array."""
    configured = config.get("agent_command")
    if configured:
        if isinstance(configured, str):
            return [configured]
        if isinstance(configured, list) and configured:
            return [str(item) for item in configured]
        raise ValueError("config 'agent_command' must be a string or list of strings")

    for name in AGENT_CLIS:
        if shutil.which(name):
            return [name, "run"]
    return []


def build_prompt(config: dict, task, task_section: str) -> str:
    """Assemble the full session prompt (master template + task brief + state)."""
    template_path = REPO_ROOT / config.get("prompt_template", "scripts/autonomous_agent_prompt.md")
    template = (
        template_path.read_text(encoding="utf-8")
        if template_path.exists()
        else "# AUTONOMOUS AGENT PROMPT\n"
    )

    result = read_state(PROGRESS_PATH)
    state = result.state

    layers = task.layers
    gates = ", ".join(sorted(layers)) if layers else "relevant"

    return f"""{template}

---

## SESSION BRIEF (generated by the runner)

- Current task: **{task.id} | {task.title}**
- Task depends on: {", ".join(task.dependencies) or "none"}
- Layers this task touches: {gates}
- Next task after this one: {state.get('next_task')}

### Task definition (authoritative: TASKS.md)

```
{task_section.strip()}
```

### Instructions for THIS session

1. Implement ONLY `{task.id}` per the definition above and `AGENTS.md`.
2. Run the {gates} test gates and the task's acceptance tests. Never fake PASS.
3. Perform a security review relevant to the task's components.
4. Commit exactly once: `TASK-{task.num:03d}: <short title>`.
5. Update `docs/AUTONOMOUS_PROGRESS.md` (mark the task PASS, set next_task).
6. Write `docs/AUTONOMOUS_HANDOFF.md` if you are stopping before commit.
7. Do not modify protected source-of-truth documents.
"""


def run_agent(argv: list[str], prompt: str, cwd: Path = REPO_ROOT) -> int:
    """Run the coding agent as a subprocess. Returns the exit code.

    If the agent CLI accepts a prompt on stdin it is passed there; otherwise we
    write the prompt to a temp file and append its path. Detection order:
    - ``opencode run`` / ``claude run`` read the prompt from argv.
    - The generic fallback appends the prompt file path.
    """
    if not argv:
        raise ValueError("no coding agent configured (set agent_command or install one)")

    try:
        proc = subprocess.run(
            argv + [prompt],
            cwd=str(cwd),
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=3600,
            check=False,
        )
        return proc.returncode
    except subprocess.TimeoutExpired:
        print("[runner] coding agent timed out (3600s).")
        return 2
    except FileNotFoundError:
        print(f"[runner] coding agent not found: {argv[0]}")
        return 127


def write_blocker(task_id: str, reason: str, evidence: str) -> None:
    entry = {
        "task": task_id,
        "blocker": reason,
        "evidence": evidence,
        "timestamp": read_state(PROGRESS_PATH).state.get("last_updated", ""),
        "resolution": "product or architecture decision required",
    }
    try:
        existing = json.loads(BLOCKERS_PATH.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        existing = {"blockers": []}
    existing.setdefault("blockers", []).append(entry)
    BLOCKERS_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"[runner] BLOCKER recorded for {task_id}: {reason}")


def derive_completed_from_git() -> list[str]:
    """Fallback: if progress file is missing, infer completed tasks from git log."""
    committed = git_log_tasks()
    ordered: list[str] = []
    for task_id in committed:
        if task_id.startswith("TASK-"):
            ordered.append(task_id)
    return ordered


def ensure_state(config: dict) -> dict:
    """Bootstrap state if missing (from git history) and reconcile with git."""
    result = read_state(PROGRESS_PATH)
    state = result.state
    if result.recovered or not state.get("completed_tasks"):
        git_tasks = derive_completed_from_git()
        if git_tasks:
            state["completed_tasks"] = git_tasks
            state["current_status"] = "RESUMED"
        write_state(state, PROGRESS_PATH)
    return state


def determine_next(state: dict, tasks, config: dict) -> str | None:
    completed = set(state.get("completed_tasks", []))
    current = find_current_task(tasks, completed, config.get("start_task"))
    if current is None:
        return None
    # find the task after current in dependency order for the "next" display
    remaining = [t for t in tasks if t.is_mvp and t.id not in completed and t.id != current.id]
    ordered = sorted(remaining, key=lambda t: t.num)
    return ordered[0].id if ordered else None


def print_status(state: dict, config: dict, tasks, agent: list[str]) -> None:
    current = state.get("current_task") or "none"
    print("=" * 60)
    print("AUTONOMOUS RUNNER — STATUS")
    print("=" * 60)
    print(f"Repository root : {REPO_ROOT}")
    print(f"Runner version  : {state.get('runner_version')}")
    print(f"Current task    : {current}")
    print(f"Current state   : {state.get('current_status')}")
    print(f"Last completed  : {state.get('last_completed_task')}")
    print(f"Next task       : {state.get('next_task')}")
    print(f"Completed tasks : {', '.join(state.get('completed_tasks', [])) or '(none)'}")
    print(f"Failed tasks    : {', '.join(state.get('failed_tasks', [])) or '(none)'}")
    print(f"Retry count     : {state.get('retry_count')}")
    print(f"Last commit     : {state.get('last_commit')}")
    print(f"Last test status: {state.get('last_test_status')}")
    print(f"Current blocker : {state.get('current_blocker')}")
    print(f"Handoff state   : {'required' if state.get('context_handoff_required') else 'ok'}")
    print(f"Agent command   : {' '.join(agent) if agent else 'NOT DETECTED'}")
    print(f"Git clean       : {not git_status_lines()}")
    print("=" * 60)


def dry_run(config: dict, state: dict, tasks, agent: list[str], current, next_task) -> None:
    print("=" * 60)
    print("AUTONOMOUS RUNNER — DRY RUN (no changes made)")
    print("=" * 60)
    print(f"Repository root : {REPO_ROOT}")
    print(f"Current task    : {current.id} | {current.title}" if current else "Current task    : none")
    print(f"Next task       : {next_task}" if next_task else "Next task       : none")
    print(f"Configured agent: {' '.join(agent) if agent else 'NOT DETECTED'}")
    print(f"Retry policy    : max_task_retries={config['max_task_retries']}, "
          f"max_session_restarts={config['max_session_restarts']}")
    print(f"Session policy  : max_tasks_per_session={config['max_tasks_per_session']}, "
          f"auto_commit={config['auto_commit']}")
    print(f"Context handoff : threshold={config['context_threshold']}")
    print("Expected action :", (
        f"launch agent to implement {current.id} then commit"
        if current else "no incomplete task — run final verification")
    )
    print("=" * 60)


def write_final_report(state: dict) -> None:
    report = {
        "status": "COMPLETE",
        "tasks_completed": state.get("completed_tasks", []),
        "last_commit": state.get("last_commit"),
        "note": "MVP tasks in TASKS.md (001-030) have been executed by the autonomous runner.",
    }
    FINAL_REPORT_PATH.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Autonomous orchestrator for the repo")
    parser.add_argument("--dry-run", action="store_true", help="show plan without acting")
    parser.add_argument("--status", action="store_true", help="print current state")
    parser.add_argument("--resume", action="store_true", help="resume from saved state")
    parser.add_argument("--stop", action="store_true", help="set graceful stop flag")
    args = parser.parse_args()

    config = load_config()
    tasks = discover_tasks(TASKS_MD)
    agent = detect_agent(config)
    state = ensure_state(config)

    if args.stop:
        STOP_FLAG_PATH.write_text("stop requested\n", encoding="utf-8")
        print("[runner] stop flag set — will stop after current safe operation.")
        return 0

    current = find_current_task(
        tasks,
        set(state.get("completed_tasks", [])),
        config.get("start_task"),
    )
    next_task = determine_next(state, tasks, config)

    if args.status:
        print_status(state, config, tasks, agent)
        return 0

    if args.dry_run:
        dry_run(config, state, tasks, agent, current, next_task)
        return 0

    # ---- normal run / resume loop ----
    session_restarts = 0
    print(f"[runner] starting at current task: {current.id if current else '(none)'}")

    while current is not None:
        if STOP_FLAG_PATH.exists():
            print("[runner] stop flag detected — stopping gracefully.")
            STOP_FLAG_PATH.unlink(missing_ok=True)
            return 0

        if config.get("require_clean_git") and git_status_lines():
            print("[runner] working tree not clean; writing handoff and stopping.")
            write_handoff(state, next_action="Review git status and commit/stash before resuming.")
            return 2

        if config.get("max_tasks_per_session", 1) > 0 and session_restarts >= config["max_tasks_per_session"]:
            print(f"[runner] reached max_tasks_per_session={config['max_tasks_per_session']}; stopping.")
            write_handoff(state, next_action=f"Resume with {current.id}.")
            return 0

        task_section = get_task_section(TASKS_MD, current)
        mark_current_task(state, current.id)
        state["next_task"] = next_task
        write_state(state, PROGRESS_PATH)

        retries = 0
        while retries <= config["max_task_retries"]:
            prompt = build_prompt(config, current, task_section)
            if agent:
                print(f"[runner] launching agent for {current.id} (attempt {retries + 1})")
                exit_code = run_agent(agent, prompt)
            else:
                print("[runner] no coding agent configured — cannot execute. Stopping.")
                write_blocker(
                    current.id,
                    "no coding agent CLI detected",
                    "config/autonomous.json 'agent_command' is null and no known CLI found",
                )
                return 3

            state = read_state(PROGRESS_PATH).state
            if state.get("current_task") is None and current.id in state.get("completed_tasks", []):
                print(f"[runner] {current.id} marked PASS. Moving on.")
                break

            retries += 1
            reason = f"agent exit code {exit_code}; task not marked PASS"
            mark_task_failed(state, current.id, reason)
            write_state(state, PROGRESS_PATH)
            if retries <= config["max_task_retries"]:
                print(f"[runner] retrying {current.id} (attempt {retries + 1}/{config['max_task_retries'] + 1})")
            else:
                write_blocker(current.id, reason, "agent exit code + state not updated after retries")
                return 4

        session_restarts += 1
        state = read_state(PROGRESS_PATH).state
        completed = set(state.get("completed_tasks", []))
        current = find_current_task(tasks, completed, config.get("start_task"))
        next_task = determine_next(state, tasks, config)
        if current:
            state["next_task"] = next_task
        write_state(state, PROGRESS_PATH)

    # All tasks complete
    print("[runner] no incomplete tasks remain.")
    if config.get("final_verification"):
        print("[runner] running final verification...")
        results = run_gates_for_layers({"frontend", "rust", "worker"})
        for layer, gates in results.items():
            for gate, status in gates.items():
                print(f"  [{layer}] {gate}: {status}")
    write_final_report(state)
    print("[runner] DONE.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
